apiVersion: v1
kind: Pod
metadata:
  name: sample8
spec:
  containers:
    - name: sample8
      image: nginx
      env:
        - name: URL
          value: foofle.com
      envFrom:
        - ConfigMapRef:
            name: sample-conf
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sample-conf
data:
  URL1: eamplea.com